tools:
  - class_name: "recipe.demystify.reward.CustomSandboxFusionTool"
    config:
      sandbox_fusion_url: "http://localhost:8081/run_code"
      num_workers: 4
      enable_global_rate_limit: true
      rate_limit: 8
      default_timeout: 45
      default_language: "python"
      memory_limit_mb: 2048
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]
